// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://qtvotxvzuzflhjxjv22weuc4ue.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": process.env.NEXT_PUBLIC_API_K,
    "aws_user_files_s3_bucket": "nitron-dashboard04330-prod",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
